### ISSUE TITLE
service start_time after end_time

### ISSUE THREAD

**Issue by parisni** [MIT-LCP/mimic-omop#26]
Apparently 167 services do have a bug in the omop etl since their start date is after the end time.

The french data provides both ward and service information too. I cannot imagin a better way of storing this information.

The alternative is to link the services directly to visit_occurrence. However this does not allow to store the parent_id linked to ward: some service cover multiple ward but only one parent_id is available. Then the way of knowing how ward and services are related would be based on calculus based on datetime that is a waste of time.

In the meantime, if we consider to propose an optimised version of omop, then this question will be reconsidered, and we will find a way to link efficiently the service information then.

That's why I suggest to go with a consistent focused version and implement the alternative way. 

Any thought ?

**Comment by alistairewj** [comment]
Not 100% sure I follow - I think we agreed that storing both services and transfers in the visit_detail table was a good solution. Is that what you propose we keep?

**Comment by parisni** [comment]
yes both ways are in visit detail but:
1) as we did (3 levels, service linked to ward with parent_id)
`  visit_occurrence -> visit_detail_ward -> visit_detail_service`
2) an olternative way (2 levels both linked to visit_occurrence, no use of parent_id)
```
 visit_occurrence -> visit_detail_ward
                  -> visit_detail_service
```
