### ISSUE TITLE
Should `qualifier` in scripts for procedure_occurrence be `modifier`?

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/mimic-omop#37]
Got this error when rerunning the ETL

```
psql:omop/build-omop/postgresql/mimic-omop-alter.sql:70: ERROR:  column "qualifier_source_value" of relation "procedure_occurrence" does not exist
```

Looking at the docs https://github.com/OHDSI/CommonDataModel/wiki/PROCEDURE_OCCURRENCE - should this instead refer to modifier?

**Comment by parisni** [comment]
Looks like they updated the model in between:
The ddl are there omop/build-omop/postgresql/omop_ddl_comments.sql
We might make them update,
but right now the ETL is sync with the above

2018-03-26 19:46 GMT+02:00 Alistair Johnson <notifications@github.com>:

**Comment by alistairewj** [comment]
OK sounds good. I am refactoring the ETL, perhaps we could have a call tomorrow if you are available.
