### ISSUE TITLE
gcpt_note_section_to_concept

### ISSUE THREAD

**Issue by rocholla** [MIT-LCP/mimic-omop#40]
where does the table gcpt_note_section_to_concept come from?

**Comment by alistairewj** [comment]
By running `Rscript etl/ConceptTables/loadTables.R mimiciii` it is generated on the mimiciii schema

See https://github.com/MIT-LCP/mimic-omop/blob/dev/README-run-etl.md for details

**Comment by chichukw** [comment]
Hi, I am following the instructions for the mimic mapping to the OMOP CDM model. However, I ran the previous rscript and am now trying to run the etl using this code: psql "$MIMIC" --set=OMOP_SCHEMA="$OMOP_SCHEMA" -f "etl/etl.sql" but there is an error at gcpt_note_section_to_concept saying that the relation does not exist...What could be the problem?
