### ISSUE TITLE
Hard-coded absolute path in loadTables.R

### ISSUE THREAD

**Issue by smondet** [MIT-LCP/mimic-omop#46]
See
https://github.com/MIT-LCP/mimic-omop/blob/master/etl/ConceptTables/loadTables.R#L50

With the absolute path, the script silently does not load the CSVs, and then `etl.sql` fails on a missing table:
`gcpt_note_section_to_concept` (Cf. #40 )

**Comment by parisni** [comment]
Thanks for your feedback !
