### ISSUE TITLE
complete sharing of this work (do not stop half way) (limited set of tables (partial person, partial visit, partial condition, partial measurement)

### ISSUE THREAD

**Issue by vojtechhuser** [MIT-LCP/mimic-omop#60]
This project makes 50 folks do the same thing. Instead, at the end of this project, a converted MIMIC III dataset in OMOP format should be offered for download. If this would be done, MIMIC III would be even more famous and cited and used and benefit research.

**Comment by tompollard** [comment]
@vojtechhuser I'm not clear what you are suggesting here. The repository is openly available, which surely allows people to build on this work? If you'd like to contribute, we'd welcome pull requests.

Mapping to OMOP is a goal, but it needs to be prioritized against other tasks, like releasing the next version of MIMIC.

**Comment by alistairewj** [comment]
We're more than happy to accept PRs.

I also believe reproducing the process is illuminating for those who want to understand the data. It's not a waste of time. Given that the conversion is incomplete, it's even more important that people understand the steps, otherwise they may falsely believe that there is a complete MIMIC-OMOP.

**Comment by vojtechhuser** [comment]
Thank you for responses.

We do want to do work and PRs.

The problem with this goal is that it can not be a simple PR for a partially converted OMOP set of CSV files. Because PR and github is not the avenue to do it properly. It can not expose the finished CSV on GitHub.  So action by data owner for this goal is the only way to do it. 

The context of "partial and imperfect" is perfectly fine framework for this.

**Comment by tompollard** [comment]
> The problem with this goal is that it can not be a simple PR for a partially converted OMOP set of CSV files. Because PR and github is not the avenue to do it properly. It can not expose the finished CSV on GitHub. So action by data owner for this goal is the only way to do it.

Why does your inability to share data mean that you are unable to contribute? MIMIC is version-controlled and publicly available, so you are equally able to work on this task. 

If you wish to demonstrate code alongside its output, perhaps you could use the MIMIC demo (https://alpha.physionet.org/content/mimiciii-demo/1.4/).

Once we have an acceptable version of MIMIC in OMOP, then we can of course share it via PhysioNet, with the same access control as the original dataset.

**Comment by aparrot89** [comment]
Hi,
I didn't know you want to provide MIMIC in OMOP format directly in PhysioNet! That's cool.

Indeed the MIMIC-OMOP dataset is not perfect at all. But nothing is perfect!

By the way in PARIS hospitals with use MIMIC in OMOP format to teach and to build algorithms that will be easily put in OMOP Paris dataset
And French hospitals are organizing a worldwide datathon in OMOP format : https://interchu.frama.io/website

**Comment by vojtechhuser** [comment]
The demo data are indeed very helpful.

**Please let me know if sharing using the same license and in this mode would be welcomed by the PhysioNet team.** And if not, please let me know what I can change to be more aligned.

I used just one OMOP table as example and rather rudimentary form (and only a draft). But the final product would have 5+ OMOP tables and would be better. The posting form and license would not change though.

https://github.com/vojtechhuser/project/tree/master/mdata

**Comment by alistairewj** [comment]
I don't think it's that clean to put the dataset on GitHub in that way. Perhaps @aparrot89 could publish it in the new PhysioNet?

**Comment by aparrot89** [comment]
Hello,

@alistairewj  @tompollard. There is no problem to push the current MIMIC-OMOP data set (v5).

We are currently working with the new version of OMOP (v6) on :
- MICROBIOLOGY: there are two issues on the OMOP wiki (https://github.com/OHDSI/CommonDataModel/issues/281 and https://github.com/OHDSI/CommonDataModel/issues/265)
If you want to participate, you are welcome.

- @parisni codes an algorithm to standardize OMOP (https://framagit.org/interchu/omop-spark/tree/master/omop-spark-standardize). It extended the local OMOP field (*_source_concept_id and *_source_value) to standard fields (*_concept_id). We use it to build the OMOP data set for the 6 French hospitals participating in the interCHU datathon.
The main advantage is to standardize the construction of the OMOP data set. 
If you want to participate, you are welcome

**Comment by vojtechhuser** [comment]
It is nice to e-meet you  aparrot89. Can you please provide some contact info for you. (or your name...). . I guess the goal is to create a project inside PhysioNet. We can collaborate there. I created one but it seems like Alistair singled out you as their pick.

**Comment by vojtechhuser** [comment]
![image](https://user-images.githubusercontent.com/7526119/62710908-26600180-b9c6-11e9-9339-4b66d5627e14.png)

**Comment by alistairewj** [comment]
As @aparrot89 did a bulk of the work in the transformation it is important that he is the author of the data publication. The data publications require extensive detail in order to ensure reusability. Adrien contacted me offline so I'll give him some advice on the process.

**Comment by vojtechhuser** [comment]
There was an interesting discussion at OHDSI call today. @alistairewj , did you get a chance to point Adrien to how to initiate the project on PhysioNet and the admins to approve it. (perhaps)

**Comment by alistairewj** [comment]
Yeah I gave Adrien ( @aparrot89 ) instructions so I'm sure he will submit
the project when he has the time!

**Comment by tomseinen** [comment]
Any updates on sharing a complete version of mimiciii in omop on physionet?

Especially now in Covid19 times, I would very much like to work with a proper cdm at home, as I can't access my organisation's cdm.
